### ISSUE TITLE
Добавить Mattermost

### ISSUE THREAD

**Issue by udjinpro** [CB9TOIIIA/simplecallback_fork_cb9t#1]
**Здравствуйте!** <p>Хотелось бы видеть кроме Slack и прочего ещё и Mattermost https://docs.mattermost.com/developer/api.html
Штука популярная у Dev и ChatOps.

**Comment by CB9TOIIIA** [comment]
Fix - будет в релизе следующем.

**Comment by CB9TOIIIA** [comment]
Скрины:

![](http://img-fotki.yandex.ru/get/194778/77677229.88/0_ac6fe_59d09a9b_orig.png)  

![](http://img-fotki.yandex.ru/get/108697/77677229.88/0_ac6ff_f39b20e2_orig.png)  

![](http://img-fotki.yandex.ru/get/194549/77677229.88/0_ac700_cf95ddd2_orig.png)  

![](http://img-fotki.yandex.ru/get/221708/77677229.88/0_ac701_9214a27c_orig.png)  

![](http://img-fotki.yandex.ru/get/195990/77677229.88/0_ac702_c61e9358_orig.png)  

![](http://img-fotki.yandex.ru/get/177849/77677229.88/0_ac703_a481501f_orig.png)  

![](http://img-fotki.yandex.ru/get/218038/77677229.88/0_ac704_381c5343_orig.png)  

![](http://img-fotki.yandex.ru/get/168237/77677229.88/0_ac705_8b00275c_orig.png)  

![](http://img-fotki.yandex.ru/get/366459/77677229.88/0_ac706_257a156_orig.png)
