### ISSUE TITLE
SyntaxError: The expression is not a legal expression.

### ISSUE THREAD

**Issue by shlange** [CB9TOIIIA/simplecallback_fork_cb9t#2]
> [NoScript XSS] Отфильтрован подозрительный запрос. URL: [https://money.yandex.ru/embed/shop.xml?account=41001223198771&quickpay=shop&payment-type-choice=on&mobile-payment-type-choice=on&writer=seller&targets=%D0%9D%D0%B0+%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D1%8B+%28%D0%BA%D0%BE%D1%84%D0%B5%2C+%D1%87%D0%B0%D0%B9%2C+%D0%BF%D0%B5%D1%87%D0%B5%D0%BD%D1%8C%D0%BA%D0%B8%29&targets-hint=&default-sum=100&button-text=01&comment=on&hint=&successURL=]. Запрос последовал со страницы: [https://myjbzoostat.cb9t.ru/simple.php]. Отфильтрованный адрес: [https://money.yandex.ru/#71797229612126390]

> Load denied by X-Frame-Options: https://money.yandex.ru/new#71797229612126390 does not permit framing.

**Comment by CB9TOIIIA** [comment]
Добрый день. Форма доната от Yandex.
